declare module 'grandiose'
declare module 'redux-electron-store'
declare module 'rtf-parse'
declare module 'rtf-parse/src/rtf/model/Document.js'
declare module 'rtf-parse/src/rtf/model/Command.js'
declare module 'rtf-parse/src/rtf/model/Group.js'
declare module 'rtf-parse/src/rtf/model/Text.js'
